spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HRMS
    username: root
    password: tien2004
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
mybatis:
  type-aliases-package: com.example.hrms.biz.booking.model,com.example.hrms.biz.department.model,com.example.hrms.biz.meetingroom.model,com.example.hrms.biz.request.model,com.example.hrms.biz.role.model,com.example.hrms.biz.user.model